# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is admin')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=10, verbose_name='phone number')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('about', models.CharField(blank=True, max_length=255, verbose_name='about')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('short_name', models.CharField(blank=True, max_length=20, verbose_name='short name')),
                ('full_name', models.CharField(max_length=50, verbose_name='full name')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=10, verbose_name='phone number')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('about', models.CharField(blank=True, max_length=255, verbose_name='about')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='last name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('gender', models.NullBooleanField(choices=[(0, 'Femme'), (1, 'Homme')], verbose_name='gender')),
                ('newsletter_subscription', models.BooleanField(default=False, verbose_name='newsletter')),
            ],
            options={
                'verbose_name': 'user profile',
            },
        ),
        migrations.CreateModel(
            name='OrganisationGroup',
            fields=[
                ('basegroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.BaseGroup')),
            ],
            bases=('profiles.basegroup',),
        ),
        migrations.CreateModel(
            name='Shroom',
            fields=[
                ('organisation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.Organisation')),
                ('api_url', models.URLField(verbose_name='API URL')),
            ],
            options={
                'abstract': False,
            },
            bases=('profiles.organisation',),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(through='profiles.GroupMembership', to='profiles.BaseGroup', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='main_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile', verbose_name='main contact'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.BaseGroup', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='basegroup',
            name='members',
            field=models.ManyToManyField(through='profiles.GroupMembership', to='profiles.UserProfile', verbose_name='members'),
        ),
        migrations.AddField(
            model_name='organisationgroup',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Organisation', verbose_name='organisation'),
        ),
    ]
