# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basegroup',
            options={'verbose_name': 'group'},
        ),
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'verbose_name': 'group membership', 'verbose_name_plural': 'group memberships'},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name': 'Organisation'},
        ),
        migrations.AlterModelOptions(
            name='organisationgroup',
            options={'verbose_name': 'Organisation group', 'verbose_name_plural': 'Organisation groups'},
        ),
        migrations.AlterField(
            model_name='organisationgroup',
            name='organisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Organisation', verbose_name='organisation'),
        ),
    ]
