# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170125_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='basegroup',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='description'),
        ),
    ]
