# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0006_basegroup_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(verbose_name='API URL')),
                ('is_self', models.BooleanField(default=False, validators=[profiles.validators.validate_is_self], verbose_name='Set this shroom and organisation as self')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Organisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shroom', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
