# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20170130_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouprole',
            old_name='role',
            new_name='name',
        ),
    ]
