# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20170130_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
            ],
        ),
        migrations.AlterField(
            model_name='grouprole',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='profiles.BaseGroup', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.OrganisationType', verbose_name='organisation type'),
        ),
        migrations.AlterField(
            model_name='organisationgroup',
            name='organisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_group', to='profiles.Organisation', verbose_name='organisation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='newsletter_subscription',
            field=models.BooleanField(default=False, verbose_name='subscribed to newsletter'),
        ),
    ]
