# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 14:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateField(auto_now_add=True, verbose_name='start date')),
            ],
            options={
                'verbose_name': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price')),
                ('duration', models.DurationField(default=datetime.timedelta(365), verbose_name='duration')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('status', model_utils.fields.StatusField(choices=[('Actif', 'Actif'), ('Participant', 'Participant')], default='Actif', max_length=100, no_check_for_status=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'subscription type',
            },
        ),
        migrations.CreateModel(
            name='Adherent',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('profiles.userprofile',),
        ),
        migrations.AddField(
            model_name='subscription',
            name='adherent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile', verbose_name='adherent'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adherents.SubscriptionType', verbose_name='subscription type'),
        ),
    ]
