# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_basegroup_description'),
        ('adherents', '0002_auto_20170124_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdherentGroup',
            fields=[
                ('basegroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.BaseGroup')),
                ('status', models.CharField(max_length=50, verbose_name='status')),
            ],
            bases=('profiles.basegroup',),
        ),
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='status',
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profiles.BaseGroup', verbose_name='group'),
            preserve_default=False,
        ),
    ]
