# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0003_auto_20170126_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adherents.AdherentGroup', verbose_name='group'),
        ),
    ]
