# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0006_auto_20170130_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='adherent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='profiles.UserProfile', verbose_name='adherent'),
        ),
    ]
