# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0007_auto_20170130_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date_end',
            field=models.DateField(default=None, editable=False, verbose_name='expiration date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_begin',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='start date'),
        ),
    ]
