# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0008_auto_20170130_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='time created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_end',
            field=models.DateField(blank=True, verbose_name='expiration date'),
        ),
    ]
