# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 10:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0009_auto_20170130_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_begin',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='start date'),
        ),
    ]
