# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adherent',
            name='userprofile_ptr',
        ),
        migrations.AddField(
            model_name='adherent',
            name='profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actors.UserProfile'),
            preserve_default=False,
        ),
    ]
