# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20170122_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adherent',
            name='profile',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='adherent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.UserProfile'),
        ),
        migrations.DeleteModel(
            name='Adherent',
        ),
    ]
