# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20170120_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='adherent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='actors.Adherent'),
            preserve_default=False,
        ),
    ]
