# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_auto_20170123_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('actors.userprofile',),
        ),
    ]
