# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_subscription_adherent'),
    ]

    operations = [
        migrations.AddField(
            model_name='actorgroup',
            name='name',
            field=models.CharField(default='kanar', max_length=50),
            preserve_default=False,
        ),
    ]
