# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_adherent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='adherent',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_type',
        ),
        migrations.DeleteModel(
            name='Adherent',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionType',
        ),
    ]
